server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      routes:
        - id: entradas-service
          uri: http://localhost:8001/
          predicates:
            - Path=/entradas/**
        - id: salidas-service
          uri: http://localhost:8083/
          predicates:
            - Path=/salidas/**
        - id: resumen-service
          uri: http://localhost:8082/
          predicates:
            - Path=/resumen/**